version: '3.8'

services:
  flask-hls-app:
    build: .
    image: flask-hls-app-prod:1.1
    container_name: flask-hls-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis-cache
      - VIDEO_SERVER_HOST=host.docker.internal
      - VIDEO_SERVER_PORT=8080
    depends_on:
      - redis-cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_USER=default
      - REDIS_PASSWORD=default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped