apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hls-app
  namespace: default
  labels:
    app: flask-hls-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hls-app
  template:
    metadata:
      labels:
        app: flask-hls-app
    spec:
      containers:
      - name: flask-app
        image: prabhanjan953/flask-hls-app-prod:1.2
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"  # Using Kubernetes service name
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "user"   # Using the password from our Redis secret
        - name: VIDEO_SERVER_HOST
          value: "http://storage-video-prab.s3.amazonaws.com/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"